### ISSUE TITLE
Compilation error for libmtpixy

### ISSUE THREAD

**Issue by blippy** [matyler/mtCellEdit#1]
There is a prototype mismatch in libmtpixy ...

libmtpixy/src/mtpixy.h:509:
`int save_gif ( char const * filename ) const;`

whereas in libmtpixy/src/px_file_gif.cpp:325:
`int mtPixy::Image::save_gif (
	char	const	* const	ARG_UNUSED ( filename )
	)
{
	return 1;
}`

Presumably the latter should read:
`int mtPixy::Image::save_gif (char const * ARG_UNUSED ( filename )) const
{
	return 1;
}`

There are other compilation errors in that dir; for example, in px_file_jpeg.cpp. Please recompile that dir.

[Without wishing to harp on the whole subject of autotools, a build system which built the whole source tree from root might have detected this issue. Building dirs independently allows bugs like this to slip in under the radar].

**Comment by matyler** [comment]
Thanks for spotting this bug.  I have just fixed this on my local system, and another bug that this compile error hid from view.

The cause of the bug you reported was the fact that I had made libpng, libjpeg, and giflib an optional dependency rather than a hard one.  Because of this there were 2 code paths separated by our old friend "ifdef", and I had failed to check the less likely option of disabling these libraries.

Considering these 3 libraries are so ubiquitous on all GNU/Linux systems I think its probably worth making these 3 libraries a hard dependency and simplifying both the C++ source code and also the build system as there would be no need to support --disable-libpng --disable-libgif --disable-libjpeg.

This case is especially persuasive with libpng as without it the painting functions are rendered useless as no brush shapes or patterns can be loaded!

Let me know if you agree or disagree with my reasoning.

**Comment by blippy** [comment]
I agree with your reasoning. If the libraries are ubiquitous, we might as well have them.

I hadn't actually tried to disable the features, BTW, I just went for a straight compile.

**Comment by matyler** [comment]
Thanks for the feedback.  I have just updated the public source code to fix the bugs and make the libraries a hard dependency.

The straight compile you mention looks to have been without -DU_GIF -DU_JPEG -DU_PNG so those features weren't rolled into the library when compiled.  In addition, several of my hand built scripts have other items passed to the compiler such as:

-DVERSION="\"libmtcelledit 3.0.2017.0402.0958"\"
-DAPP_NAME="\"libmtCedUI"\"
-DU_TK_QT5
-DVERSION="\"mtCedCLI 3.0.2017.0402.0958"\" -DBIN_NAME="\"mtcedcli"\"
-DBIN_NAME="\"mtcelledit-qt5"\"

I would guess that the autotools have some way of accommodating these things?  The version number sits inside the file VERSION so this may be automated somehow.  The Qt one is worth noting in particular as different distros install Qt differently, and so the way to integrate the MOC tool will vary from system to system.  My method sits at the end of the file mtConf.txt inside 2 functions.
