### ISSUE TITLE
Generated files should not be under source control

### ISSUE THREAD

**Issue by blippy** [matyler/mtCellEdit#4]
I noticed in the diff file of commit https://github.com/matyler/mtCellEdit/commit/29deb11935be7f75e475382af5fc3333d46b936c that generated files such as mtcedutils/man/cedappend.1.gz have been added to the repo. 

**The golden rule is: files which are generated should not go in source control.** This includes manpages, files generated during configuration, files generated by bison/yacc,  etc.. 

What you should do is: delete the .gz files. commit, and add the file `.gitignore` to the top level of your directory:

    *.gz

Then `git add .gitignore` then `git commit .gitignore`. That way, when *.gz are generated again, git won't flag them up for attention. `.gitignore` does not have to be in the project's root directory, they can be sprinkled throughout the project tree. [Here's some documentation](https://help.github.com/articles/ignoring-files/)

**Comment by matyler** [comment]
The problem with applying this rule is that it would also require me to remove the handbook HTML files as they too are generated by txt2tags.  But if that happens then there is no handbook to read about how to build things!

The man pages are visible because they are automatically updated each time there is a new version, which is necessary to conform to man page convention regarding version numbers and the date the man page was last modified.  Using .gitignore would lose this information, and is therefore undesirable.

I'm not sure it is possible to obey the git rules and also the handbook/man page rules at the same time.

The link you gave also links to a page suggesting that .gz files should be kept unpacked.  Is this a possible solution?  Even unpacked, these files would still need to change each version, but instead of being binary files they would have diff text changes that would only affect the version and date line at the top of the .1 file.

**Comment by blippy** [comment]
There's a curcularity here: you're saying that the instructions on how to build are built by the builder. In that case, remove the build instructions from the html file, and put them in a plain-text file called `INSTALL` in the top level directory.

> The man pages are visible because they are automatically updated each time there is a new version

OK, so the man pages are generated every time there's a new version. Make them using `make`, and install them using `make install`, just like you do with binaries. The binaries shouldn't be under source control, either.

Perhaps there's been a misunderstanding. To clarify, you can generate files within project directories, but you shouldn't commit them to the repository.

The .gz files can be packed, that's OK. They're generated by the build, ready for installation in their proper form.

Let me know if you're still unclear.

**Comment by matyler** [comment]
With regards to the HTML, the top level file README.txt instructs the user to read the HTML handbook in the given directory, which requires zero effort other than opening a browser.  I'm not keen to ask users to build something before they can read the handbook, as it places a needless burden on them.  I'm not keen to have users read new plaintext files, or just the HTML .t2t sources, as this is less convenient than reading HTML in a web browser.

Man pages are slightly different in that they can be built at compile time, but a text file would need to be created at packaging time to store the modification date somewhere (git doesn't store file datestamps so we have no choice here).  This file would itself then appear on the git changes for each version as it would change each day.  Then txt2tags would also become a build dependency, as currently that work is done by my automated script at packaging time.

In both cases I feel changing the current behaviour adds a burden to the end user, without any payoff for them.  I understand this uglifies the git history and breaks convention, but I feel this is the lesser of two evils.

**Comment by blippy** [comment]
It seems that we have a difference in philosphy, and we'll probably just have to agree to disagree.

Plain text INSTALL files are actually better than HTML *because* they don't require a browser. You just read read them, It is standard practise.

>  This file would itself then appear on the git changes for each version as it would change each day. 

You don't need to change the version each day. Development builds don't require such rigour. Why don't you just put the date that you edit a manpage in the t2t file? Isn't the date in the manpage  the date that the file was last edited

**Comment by matyler** [comment]
At the current time I would agree with you that its a kind of philosophical gap that neither of us is able to bridge, so sadly I will close the issue now.

However, in a perfect world I agree with the principle that this is a source repo and should be source only.  Also in a perfect world there would be a binary package for people to install with zero effort on their part, i.e. a deb package for Debian, a pkg package for Arch and an rpm package for Fedora, etc.  This package would hold the binaries, HTML, man pages, etc, but no source code, and would be presented using a standard software installer (e.g. Synaptic in Debian).

This contrast between pure source and pure binary packages is the tradition in the free software world, and I am happy with that in principle.

Sadly though, as a hobbyist, I don't really have the time to contribute to all of the distros and conform to their packaging standards.  Also, because mtCellEdit is a bit of a niche entity its unlikely to gain a wider appeal in the same way that mtPaint did back in 2004, so I don't see much prospect of enough people being interested enough to do some packaging.

Therefore I feel that the only thing I can practically do is to have a kind of hybrid package where the documentation is pre-built and always fully accessible to web browsers with minimal effort.

Soon, when I get time, I shall get the v3.0 HTML docs on a website somewhere (like with mtPaint), but this still doesn't solve the problems described above, it merely works around them.

**Comment by matyler** [comment]
Since I last wrote in 2017 I have created an online website to allow people to read the HTML and man page docs online, and I have also added the option of an AppImage binary.  This resolves some of the issues in my last post so I have now been able to remove the compiled man pages and the compiled html pages.  See today's GitHub commits on the develop branch for the changes.

This adds a dependency of txt2tags to the build process, but its widely supported by Linux distros so this shouldn't be a problem.

This does seem to simplify the source code and (as the latest commit shows) the diffs are cleaner.

Thanks for the suggestion!
