### ISSUE TITLE
Setup Travis CI for auto-build AppImage (portable binary packages for Linux)

### ISSUE THREAD

**Issue by Symbian9** [matyler/mtCellEdit#5]
Propose setup `master` branch to produce auto-builds using Travis CI as `.AppImage` package -- universal portable package format for most of Linux distributions.

* http://github.com/AppImage/AppImageKit
  * https://github.com/probonopd/linuxdeployqt
  * https://github.com/probonopd/uploadtool

Firstly, you need create and setup `.travis.yml` script in the root of `master` branch, for example:

* https://github.com/probonopd/linuxdeployqt/blob/master/.travis.yml
* https://github.com/leozide/leocad/blob/master/.travis.yml
* https://github.com/Symbian9/azpainter/blob/master/.travis.yml

@probonopd, please, help @matyler to solve this task! ;-)

P.S.: Known apps that already provide AppImage's listed on AppImageHub

* https://appimage.github.io/apps

**Comment by probonopd** [comment]
@matyler happy to help - please let me know if you are running into any issues.

**Comment by matyler** [comment]
Hello @probonopd  & @Symbian9 

I'm sure it would be possible to create an AppImage for mtCellEdit, but I wouldn't be able to do this myself as the task looks non-trivial.  Before I can get your help to do this I need to outline the project so you can understand the mechanics of how things are built.

The repo/tarball that contains mtCellEdit is a collection of many programs, and due to this I have had no choice but to use shared libraries.  These are outlined here, along with system dependencies:

http://doc.marktyler.org/mtcelledit/en_GB/chap_03.html

Each of the modules has its own "configure/make/make install" pattern so that is fairly easy to follow (even though I don't use the autotools).

As well as building each module manually by hand, it is also possible to use my pre-prepared build scripts which can be used to build any combination of the modules, for any Linux system.  I normally do this when I am testing and I want to use a native package management system such as Fedora/Suse RPM, Debian DEB, or Arch PKG.  For the purposes of AppImage and the YAML file I would suggest using the general "configure/make/make install" as per the outline here:

http://doc.marktyler.org/mtcelledit/en_GB/chap_03.html#SEC51

For example you could build the Qt5 version of mtCellEdit and its 5 library dependencies like this:

DIR="$HOME/test/usr"; ./build_local.sh --preconf "LDFLAGS=-Wl,-rpath=$DIR/lib" --conf "--disable-man --prefix=$DIR" libmtkit libmtcelledit libmtpixy libmtcedui libmtqex5 mtcelledit-qt5

This mechanism uses rpath to allow the libs to sit wherever you want to put them.  I'm not sure how this would work with the AppImage conventions, but I'm sure you know how this can be solved.

For the sake of consistency it would be nice to put the YAML file with the other package management scripts inside the /pkg/ directory here:

https://github.com/matyler/mtCellEdit/tree/master/pkg

Or does the Travis/YAML file have to be in the master root?

**Comment by probonopd** [comment]
`.travis.yml` needs to be in the root directory of the git repository, but you can use commands like `cd` inside it. 

> mtCellEdit is a collection of many programs,

Do you want one AppImage that contains all of those, or a separate AppImage for each of them?

**Comment by matyler** [comment]
Putting .travis.yml in the root and then "cd pkg" should allow the build scripts to work without modification.

I had naively assumed that it was one program per AppImage, but judging from your question this assumption may be wrong!

If everything can go into a single AppImage that would be great, and save a lot of juggling with multiple images.  How would this work in practice?  Presumably an image would have to be mounted somewhere and then the user could run any of the programs, or read the documentation from this read only area?

**Comment by probonopd** [comment]
> Putting .travis.yml in the root and then "cd pkg" should allow the build scripts to work without modification.

Yes.

> I had naively assumed that it was one program per AppImage, but judging from your question this assumption may be wrong!

That is the default and how I like it best (because it is so simple).

> If everything can go into a single AppImage that would be great, and save a lot of juggling with multiple images. How would this work in practice? Presumably an image would have to be mounted somewhere and then the user could run any of the programs, or read the documentation from this read only area?

One can _trick the system_ by writing a tiny bash wrapper that invokes different payload executables based on how it was called. You need to delete the AppRun symlink and replace it with a custom script. https://github.com/ImageMagick/ImageMagick/blob/master/AppRun is an example.

https://github.com/ImageMagick/ImageMagick/blob/8468717f73200ecb24c3caf06cc2fbe353347500/.travis.yml#L36-L38 shows how to replace the `AppRun` symlink with this custom script.

Hope this is sufficient to get you started; feel free to ask questions if something is not clear. cc'ing @KurtPfeifle who does real wizardry in terms of packing more than one thing into an AppImage.

**Comment by matyler** [comment]
Thanks for the info @probonopd

I shall take your advice and only put the spreadsheet program mtCellEdit into the image (probably the Qt4 version to keep things small and simple).  Maybe later I can add other images for other parts of the package, but I would like to learn to walk before I learn to run!

How does this Travis autobuild work?  Does a new AppImage get created each time I update GitHub, or does it wait for a new offical release?

**Comment by KurtPfeifle** [comment]
@probonopd wrote:

> "One can *trick the system* by writing a tiny bash wrapper"

I do not think it is justify to label this as *"tricking the system"*. This is normal system behavior, and is using it as it is designed to work. Otherwise most of IT functionality and especially all of the AppImage-wizardry should also be labelled as "tricking the system".

>  "https://github.com/ImageMagick/ImageMagick/blob/master/AppRun is an example."

Actually, this one isn't as good an example. Better look at https://github.com/KurtPfeifle/ImageMagick/blob/master/appimage/AppRun . This is my current incarnation. It supports to let users also read man pages, READMEs, HTML or PDF documentation which ships with an application.

But this still has some flaws, which I'll overcome once I re-gain some time to work on them. My intention is to come up with a generic AppRun which can be used for any multi-binary AppImage as a drop-in replacement requiring no or only very minimal modifications to work.

**Comment by probonopd** [comment]
> How does this Travis autobuild work? Does a new AppImage get created each time I update GitHub

Yes.

**Comment by probonopd** [comment]
> I do not think it is justify to label this as "tricking the system". This is normal system behavior

You are right @KurtPfeifle, the person who puts together an AppImage is free to use as the `AppRun` entry point whatever symlink or file they like, as long as it can run the main application. With "tricking" i meant "tricking `linuxdeployqt`" as it normally just uses a symlink to the main executable as the `AppRun` entry point.

**Comment by matyler** [comment]
Hello @probonopd

I built my first AppImage of my GUI apps on a Lubuntu 14.04 system earlier. I tested these on a few live DVD's.  It worked well on Slax, Gentoo, and Slackware.

Fedora 27 failed with this error:
./mtCellEdit-qt4-x86_64.AppImage: symbol lookup error: /lib64/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

I guess this is the Fedora system trying to use its own version of harfbuzz for some reason?  Something about this here perhaps:

https://bugzilla.redhat.com/show_bug.cgi?id=1410528

I had problems loading the documentation for the apps, and also the icons for mtPixy.  Does this mean that resources inside the image at /usr/share/* are not available at runtime?  Have a look at the apps here:

[apps.zip](https://github.com/matyler/mtCellEdit/files/1842131/apps.zip)

I noticed that libraries like Cairo, freetype, libpng, etc were copied across as I expected but not Pango which my app does use directly.  Is this correct?  I did find these AppImage/Pango references which may be relevant to this point:

https://discuss.pixls.us/t/rawproc-0-6-at-github-x86-64-appimage-posted/4997/11
https://discourse.appimage.org/t/what-would-cause-this/123

**Comment by probonopd** [comment]
Please upload your AppImage for analysis of the libharfbuzz issue.

Resources inside the image are __not__ available at at `/usr/share/*` but inside the temporary mountpoint to which the AppImage gets mounted during execution. So the application must take care to load resources from a path _relative_ to itself.

> I noticed that libraries like Cairo, freetype, libpng, etc were copied across as I expected but not Pango which my app does use directly. Is this correct?

Do you assume this causes issues? Please upload your AppImage for analysis and please describe the issues.

**Comment by matyler** [comment]
@probonopd I uploaded the AppImages in my previous comment.  Here is the link:
https://github.com/matyler/mtCellEdit/files/1842131/apps.zip

If you can't get access to this file, let me know and I will email them over to you.

Thanks for the tip about relative paths.  I shall see how I can overcome that issue in the build scripts.

I think we can logically deduce that it is the absence of libpango in the AppImage which is causing the harfbuzz problem:

1. On the Fedora system the AppImage is using the host systems libpangoft2-1.0.so (it can't be doing anything else as its not inside the AppImage).

2. Fedora->libpangoft2-1.0.so is linked to Fedora->libharfbuzz and **NOT** AppImage->libharfbuzz (which contains the correct symbols).  This has to be correct because /lib64/libharfbuzz.so.0 in the error message above is the Fedora library.

3. When the AppImage is run it cannot find the compiled libharfbuzz symbols because AppImage->libharfbuzz is **NOT** loaded.  This causes the crash due to missing symbols.

Ergo by including the Pango libraries inside the AppImage you resolve this problem!  This is just a theory at the moment, but it does rather neatly explain my experiences and is supported by the error messages at the command line.

I assume there is no problem in bundling the various Pango libraries into an AppImage?

**Comment by probonopd** [comment]
> I think we can logically deduce that it is the absence of libpango in the AppImage

...or we can check: `Your.AppImage --appimage-extract` :-)

> I assume there is no problem in bundling the various Pango libraries into an AppImage?

Probably not, but I am wondering why they where not bundled in the first place.

**Comment by matyler** [comment]
Well done @probonopd you have found the problem!

These 3 libraries are deliberately excluded from the AppImage:
libpangoft2-1.0.so.0
libpangocairo-1.0.so.0
libpango-1.0.so.0

Sadly this then causes the harbuzz problem I described above.

Unless there is a way of including these 3 Pango libraries, my apps won't work with AppImage on Fedora systems. :(

Can you recall the reason why Pango is excluded?  It seems a little arbitrary to bundle Cairo and Harfbuzz but not Pango.

I can understand excluding libc, libstdc++, libGL, libX11, etc. but Pango is surely too high level to exclude?  Especially considering libfreetype is lower level than Pango and that is allowed inside the AppImage.

**Comment by matyler** [comment]
@probonopd unfortunately I still can't get the AppImage binary to load resources from inside the AppImage file.  When I use a relative path like "../share/some/file" it still looks for the file in the host filesystem, i.e. $(pwd)/../share/some/file.

If I can't fix this then sadly mtPixy won't work properly from an AppImage.  :(

**Comment by probonopd** [comment]
Please don't make the path relative to PWD but relative to the main executable. Check `QCoreApplication::applicationDirPath());`.

**Comment by matyler** [comment]
Thanks for the tip about applicationDirPath() @probonopd.  I now see exactly what is happening when the AppImage starts up (i.e. using /tmp/* as the temporary mount point).

Unfortunately there is no quick easy fix for my apps as the design relies on fixed locations, so it will take a non-trivial rewrite to get mtPixy and the handbook links working.

Having said that, I don't think this stops me having an AppImage for mtCellEdit.  The only blocking problem is the Pango issue I mentioned earlier.  Should I report this as an issue on the linuxdeployqt GitHub repo?  Or maybe the fix is on its way already?

I have just uploaded the latest version of mtCellEdit, which now includes the build script to make the AppImage packages in Lubuntu 14.04 via linuxdeployqt.  I decided not to use the Travis autobuild because between the main releases the program it is in an alpha state, which means I don't want end users trying it out (only developers).  What I would prefer to do is have an AppImage for stable release such as v3.1 which I released recently.  This is very quick an easy for me to do manually inside a QEMU VM.

**Comment by probonopd** [comment]
According to https://github.com/AppImage/AppImages/blob/master/excludelist, this is to prevent https://github.com/AppImage/AppImages/issues/240 from happening:

```
# Workaround for:
# Rectangles instead of fonts
# https://github.com/AppImage/AppImages/issues/240
libpangoft2-1.0.so.0
libpangocairo-1.0.so.0
libpango-1.0.so.0
```

> Can you recall the reason why Pango is excluded? It seems a little arbitrary to bundle Cairo and Harfbuzz but not Pango.

What happens if you also _not_ bundle Harfbuzz?

**Comment by KurtPfeifle** [comment]
@matyler wrote:

> *"I decided not to use the Travis autobuild because between the main releases the program it is in an alpha state, which means I don't want end users trying it out (only developers). What I would prefer to do is have an AppImage for stable release such as v3.1 which I released recently."*

I understand that you do not want to ship alpha state software to end users.

However this isn't a reason to avoid Travis autobuilds. You can do Travis autobuilds with AppImages for every commit you do, but then automatically distinguish what to do with the build result:
 
- Is it an intermediary "continuous build" / alpha state? Then upload it to a non-public service (such as *transfer.sh* using @probonopd's *`upload.sh`* from [here](https://raw.githubusercontent.com/probonopd/uploadtool/master/upload.sh). In the Travis build log you'll get to see the download URL where your alpha build is stored at on transfer.sh and you can communicate this to your developers and alpha testers.

- Is it an officially tagged release? Then uploaded it to your publically available [GitHub releases site](https://github.com/matyler/mtCellEdit/releases).

**Comment by matyler** [comment]
I tried removing libharfbuzz on my Fedora system as you suggested @probonopd but it didn't change anything: the program still failed with the same message.  However, when I removed libfreetype everything worked perfectly.

In my opinion libharfbuzz, libgraphite2, and libfreetype should be removed/kept as a group as they are all the low level font rendering libs.  My instinct is that its too messy to have some font rendering libs from the old OS build system and some from the newer OS host.

On my test live DVD's (Fedora, Gentoo, Slackware, ArchBang, openSUSE Tumbleweed GNOME) removing these 3 libs caused no problems whatsoever and the program worked perfectly.

I also found that it was safe to remove libcairo/libpixman from the AppImage and use the host OS versions instead (I got suspicious about libcairo because libpangocairo exists on the host OS which may cause issues with a bundled AppImage version of libcairo).  Whether this is safe for all situations, I'm not sure.  For example an app that bundles GTK+2/3 may have issues, as per this thread:
https://github.com/AppImage/AppImageKit/issues/454

It seems to support my theory about removing/keeping {libharfbuzz, libfreetype, libpango} as a whole unit being a good idea.  The only issue was the GTK+2 side effect after building an AppImage on a Ubuntu 16.04 system.

Conclusion
==========
Pango, Cairo, FreeType seem to be conservative and trustworthy in terms of API/ABI and they seem to be installed on all modern distros.  Therefore they seem like good candidates for being excluded from an AppImage.  This compares to Qt, GTK+, libpng, giflib, etc. which seem to not always be present, and even if they are present the API/ABI seems too unstable to trust between different versions.  Therefore they **MUST** be bundled inside the AppImage if they are used by the app.

Before any decisions on this are made I would suggest testing my theories on complex/big GTK+2/3 based AppImage programs (e.g. Inkscape or Gimp) and simply remove the aforementioned libs.  If this succeeds it is probably safe to exclude the libs.

Caveat
------
The conclusion is based on compiling my Qt4 app on Lubuntu 14.04 and testing on modern distros.  A big change in Pango, Cairo, FreeType in the future could change things for the worse and create an unsolvable problem for an AppImage.

**Comment by matyler** [comment]
@KurtPfeifle wrote:
> However this isn't a reason to avoid Travis autobuilds. You can do Travis autobuilds with AppImages for every commit you do, but then automatically distinguish what to do with the build result:

The scenario you describe sounds fair enough.  Autobuilds do have their uses in terms of saving time and effort in the development process.  Once I have learned a bit more about Travis, AppImage, etc it may well be worth setting this up.  Thanks for the advice.

**Comment by probonopd** [comment]
> In my opinion libharfbuzz, libgraphite2, and libfreetype should be removed/kept as a group as they are all the low level font rendering libs. My instinct is that its too messy to have some font rendering libs from the old OS build system and some from the newer OS host.

Thanks for your research, this may also be relevant for https://github.com/AppImage/AppImageUpdate/issues/85#issuecomment-377492019, https://github.com/probonopd/linuxdeployqt/issues/259 and https://github.com/probonopd/linuxdeployqt/issues/261.

**Comment by matyler** [comment]
I have just uploaded an AppImage for mtCellEdit 3.1 here:
https://github.com/matyler/mtCellEdit/releases/tag/3.1
Thanks to everyone for helping me do this!

**Comment by Symbian9** [comment]
> I have just uploaded an AppImage for mtCellEdit 3.1

Please, setup also `Continuous` ("nightly") tag for auto-build for each commit too!

For example, look how @probonopd did it

- https://github.com/probonopd/linuxdeployqt/releases/tag/continuous

**Comment by matyler** [comment]
Thanks for the suggestion @Symbian9 but I decided not to implement continuous or automatic builds.

My goal with the AppImage is to help normal Linux users test mtCellEdit if they have not tried it before.  Because of this I want people to use the stable version which is released once or twice a year.

I also think its important that I personally test the binary before it is published.  By doing this I can personally vouch for what the AppImage is doing and create some trust.  With any kind of automated build this will be impossible as I don't know whether the AppImage is behaving as I would like on target systems (e.g. Live DVD's).
